@echo off
echo Building and starting containers...
docker-compose up -d --build

echo Waiting for database to be ready...
timeout /t 10 /nobreak

echo Installing test dependencies...
docker-compose exec backend pip install -r tests/requirements.txt

echo Running tests...
docker-compose exec backend python tests/test_api.py

echo Tests completed. Stopping containers...
docker-compose down 